const styles = [
  "Abah's Watch",
  "Akaviri",
  "Aldmeri Dominion",
  "Ancient Elf",
  "Ancient Orc",
  "Anequina",
  "Apostle",
  "Argonian",
  "Ashlander",
  "Assassins League",
  "Barbaric",
  "Bloodforge",
  "Buoyant Armiger",
  "Breton",
  "Celestial",
  "Daedric",
  "Daggerfall Covenant",
  "Dark Brotherhood",
  "Dark Elf",
  "Dead Water",
  "Draugr",
  "Dreadhorn",
  "Dremora",
  "Dro-m’Athra",
  "Dwemer",
  "Ebonheart Pact",
  "Ebonshadow",
  "Ebony",
  "Elder Argonian",
  "Fang Lair",
  "Glass",
  "Grim Harlequin",
  "High Elf (Altmer)",
  "Hlaalu",
  "Hollowjack",
  "Honor Guard",
  "Huntsman",
  "Imperial",
  "Khajiit",
  "Malacath",
  "Mazzatun",
  "Mercenary",
  "Militant Ordinator",
  "Minotaur",
  "Morag Tong",
  "Nord",
  "Orc",
  "Order Of The Hour",
  "Outlaw",
  "Primal",
  "Psijic",
  "Pyandonean",
  "Ra Gada",
  "Redguard",
  "Redoran",
  "Frostcaster",
  "Sapiarch",
  "Scalecaller",
  "Silken Ring",
  "Silver Dawn",
  "Skinchanger",
  "Soul Shriven",
  "Telvanni",
  "Thieves Guild",
  "Trinimac",
  "Tsaesci",
  "Welkynar",
  "Wood Elf (Bosmer)",
  "Worm Cult",
  "Xivkyn",
  "Yokudan",
  "Pellitine",
  "Coldsnap",
  "Meridian"
];

export default [
  { value: 'any', label: 'No Preference', color: '#fcb935', isFixed: true }
].concat(styles.sort().map(style => ({ value: style, label: style, color: '#2DC50E', isFixed: true })))
