export const primaryWeapons = [
  {
    value: 'gear.weapon.axe',
    label: 'gear.weapon.axe',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.mace',
    label: 'gear.weapon.mace',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.sword',
    label: 'gear.weapon.sword',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.battleAxe',
    label: 'gear.weapon.battleAxe',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.maul',
    label: 'gear.weapon.maul',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.greatsword',
    label: 'gear.weapon.greatsword',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.dagger',
    label: 'gear.weapon.dagger',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.bow',
    label: 'gear.weapon.bow',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.infernoStaff',
    label: 'gear.weapon.infernoStaff',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.frostStaff',
    label: 'gear.weapon.frostStaff',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.lightningStaff',
    label: 'gear.weapon.lightningStaff',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.restorationStaff',
    label: 'gear.weapon.restorationStaff',
    color: '#2DC50E',
    isFixed: true,
  },
];

export const secondaryWeapons = [
  {
    value: 'gear.weapon.axe',
    label: 'gear.weapon.axe',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.mace',
    label: 'gear.weapon.mace',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.sword',
    label: 'gear.weapon.sword',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.dagger',
    label: 'gear.weapon.dagger',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.shield',
    label: 'gear.weapon.shield',
    color: '#2DC50E',
    isFixed: true,
  },
];

export const weaponTraits = [
  {
    value: 'common.none',
    stone: 'common.none',
    label: 'common.none',
    color: '#fcb935',
    isFixed: true,
  },
  {
    value: 'gear.weapon.traits.charged',
    stone: 'gear.weapon.traits.defending.stone',
    label: 'gear.weapon.traits.charged',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.traits.defending',
    stone: 'gear.weapon.traits.defending.stone',
    label: 'gear.weapon.traits.defending',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'common.traits.infused',
    stone: 'gear.weapon.traits.infused.stone',
    label: 'common.traits.infused',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'common.traits.nirnhoned',
    stone: 'gear.weapon.traits.nirnhoned.stone',
    label: 'common.traits.nirnhoned',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.traits.powered',
    stone: 'gear.weapon.traits.powered.stone',
    label: 'gear.weapon.traits.powered',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.traits.precise',
    stone: 'gear.weapon.traits.precise.stone',
    label: 'gear.weapon.traits.precise',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.traits.sharpened',
    stone: 'gear.weapon.traits.sharpened.stone',
    label: 'gear.weapon.traits.sharpened',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'common.traits.training',
    stone: 'gear.weapon.traits.training.stone',
    label: 'common.traits.training',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.traits.decisive',
    stone: 'gear.weapon.traits.decisive.stone',
    label: 'gear.weapon.traits.decisive',
    color: '#2DC50E',
    isFixed: true,
  },
];

export const weaponGlyphs = [
  {
    value: 'common.none',
    label: 'common.none',
    color: '#fcb935',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.flame',
    essenceRune: 'Rakeipa',
    potency: 'additive',
    label: 'gear.weapon.glyphs.flame',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.frost',
    essenceRune: 'Dekeipa',
    potency: 'additive',
    label: 'gear.weapon.glyphs.frost',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.shock',
    essenceRune: 'Meip',
    potency: 'additive',
    label: 'gear.weapon.glyphs.shock',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.poison',
    essenceRune: 'Kuoko',
    potency: 'additive',
    label: 'gear.weapon.glyphs.poison',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.foulness',
    essenceRune: 'Haoko',
    potency: 'additive',
    label: 'gear.weapon.glyphs.foulness',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.decreaseHealth',
    essenceRune: 'Okoma',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.decreaseHealth',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.hardening',
    essenceRune: 'Deteri',
    potency: 'additive',
    label: 'gear.weapon.glyphs.hardening',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.absordHealth',
    essenceRune: 'Oko',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.absordHealth',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.absordMagicka',
    essenceRune: 'Makko',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.absordMagicka',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.absorbStamina',
    essenceRune: 'Deni',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.absorbStamina',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.weaponDamage',
    essenceRune: 'Okori',
    potency: 'additive',
    label: 'gear.weapon.glyphs.weaponDamage',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.weakening',
    essenceRune: 'Okori',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.weakening',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.crushing',
    essenceRune: 'Deteri',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.crushing',
    color: '#2DC50E',
    isFixed: true,
  },
  {
    value: 'gear.weapon.glyphs.primaticOnslaught',
    essenceRune: 'Hakeijo',
    potency: 'subtractive',
    label: 'gear.weapon.glyphs.primaticOnslaught',
    color: '#2DC50E',
    isFixed: true,
  },
];
