import { useState } from 'react';
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { Roboto } from 'next/font/google'
import { AppLayout, Button, TextArea, useTheme } from '@/burtUI'
import { discordTheme } from '@/burtUI/styles/themes';
import UserDetails from '@/components/UserDetails';
import PaymentOptions from '@/components/PaymentOptions';
import ArmorSection from '@/components/ArmorSection';
import layoutStyles from '../styles/layout.module.css';

const roboto = Roboto({ weight: '300', subsets: ['latin'] });

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by language.
      messages: (await import(`../translations/locales/${context.locale}/messages.json`)).default
    }
  };
}

export default function Home() {
  useTheme(discordTheme);

  const [requestNotes, setRequestNotes] = useState('');

  return (
    <>
      <Head>
        <title>ESO Craft Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout
        className={roboto.className}
        header={{
          logoUri: 'https://demo.esocraftrequest.com/images/hammer-and-anvil.png',
          navLinks: [],
          menu: {
            icon: <Button>Materials</Button>,
            options: []
          }
        }}
        footer={<div>Footer</div>}
      >
        <div>
          <div className={layoutStyles.limitWidth}>
            <UserDetails />
            <PaymentOptions />
            <TextArea
              label='Request notes'
              direction='inside'
              value={requestNotes}
              onChange={setRequestNotes}
              allowHorizontalResize={false}
              allowVerticalResize={false}
            />
          </div>

          <ArmorSection />
        </div>
      </AppLayout>
    </>
  )
}
