import Head from 'next/head'
import { Inter } from 'next/font/google'
import { AppLayout, Button, Switch, useTheme } from '@/burtUI'
import { discordTheme } from '@/burtUI/styles/themes';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useTheme(discordTheme);

  return (
    <>
      <Head>
        <title>ESO Craft Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout
        header={{
          logoUri: 'https://demo.esocraftrequest.com/images/hammer-and-anvil.png',
          navLinks: [],
          menu: {
            icon: <Button>Materials</Button>,
            options: []
          }
        }}
        footer={<div>Footer</div>}
      >
        <div>
          <Switch onToggle={() => window.alert('toggle')} />
        </div>
      </AppLayout>
    </>
  )
}
