import PropTypes from 'prop-types';

export default PropTypes.shape({
  display: 'gear.armor',
  head: {
    display: 'gear.armor.head',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
  shoulder: {
    display: 'gear.armor.shoulder',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
  chest: {
    display: 'gear.armor.chest',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
  legs: {
    display: 'gear.armor.legs',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
  waist: {
    display: 'gear.armor.waist',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
  hands: {
    display: 'gear.armor.hands',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
  feet: {
    display: 'gear.armor.feet',
    Quality: PropTypes.string.isRequired,
    Weight: PropTypes.string.isRequired,
    Trait: PropTypes.string.isRequired,
    Glyph: PropTypes.string.isRequired,
    'Glyph Quality': PropTypes.string.isRequired,
    Set: PropTypes.string.isRequired,
    Style: PropTypes.string.isRequired,
  },
});
