name: Update Sets

on:
  schedule:
    - cron: "0 17 * * 5" # Every Friday at 5pm

jobs:
  update-sets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Navigate to scrapers directory
        run: cd lib/scrapers

      - name: Install dependencies
        run: npm install

      - name: Run Sets Scraper script
        run: node set-scraper.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update sets"
          git push